data_sets:
- name: bittiger_train
  url: https://s3-us-west-2.amazonaws.com/us-office/competition/training.zip
  compression_format: zip
  folder_name: training
  data_format: jpg
  label_format: idl
- name: bittiger_test
  url: https://s3-us-west-2.amazonaws.com/us-office/competition/testing.zip
  compression_format: zip
  folder_name: testing
  data_format: jpg

models:
- name: ssd
  asset_urls:
  - name: ssd_300_vgg.ckpt.zip
    url: https://github.com/balancap/SSD-Tensorflow/blob/master/checkpoints/ssd_300_vgg.ckpt.zip?raw=true

videos:
- name: drive_nyc.mp4
  url: None

data_raw_dir: assets/data/raw
data_tfrecords_dir: assets/data/tfrecords

models_dir: assets/models
videos_dir: assets/videos
