train:
    data_sets:
    - bittiger_train
test:
    data_sets:
    - bittiger_test
    output_path: ./test.idl
    slide_show: True
serve:
    video: drive_nyc.mp4
    max_frame_num: 20000

model: ssd

logging: debug

# percentage of data used for validation
holdout_percentage: 0.1
